#!/bin/sh

set -o errexit
set -o nounset


python manage.py migrate
python manage.py runserver 0.0.0.0:8000

# python /app/manage.py collectstatic --noinput
# /usr/local/bin/gunicorn config.asgi --bind 0.0.0.0:8000 --chdir=/app -k uvicorn.workers.UvicornWorker --timeout 180