services:
  - type: web
    name: django
    env: production
    plan: free
    buildCommand: docker-compose -f docker-compose.yml build
    startCommand: docker-compose -f docker-compose.yml up
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
