databases:
  - name: tickethubbd
    plan: free
    databaseName: tickethub_bd
    user: tickethub_bd_user

services:
  - type: web
    plan: free
    name: tickethubapi
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tickethubbd
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4