services:
  - type: web
    name: django
    runtime: python
    plan: free
    buildCommand: docker-compose -f docker-compose.yml build
    startCommand: docker-compose -f docker-compose.yml up
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
