# Generated by Django 4.2.6 on 2023-11-28 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identification_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
