# Generated by Django 4.2.6 on 2023-11-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_google',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
