# Generated by Django 4.2.6 on 2023-12-01 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_photo_google'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloquedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date on which it was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Date it was last updated.', verbose_name='updated at')),
                ('fecha_vigencia_bloqueo', models.DateTimeField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, max_length=250, verbose_name='Observación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bloqued_users',
                'verbose_name_plural': 'bloqued_users',
                'db_table': 'bloqued_users',
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
                'managed': True,
            },
        ),
    ]
