# Generated by Django 3.2.12 on 2024-06-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_buyeventticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Comedia', 'Comedia'), ('Festival', 'Festival'), ('Exposición', 'Exposicion'), ('Deportes', 'Deportes'), ('Concierto', 'Concierto')], max_length=30),
            preserve_default=False,
        ),
    ]
