# Generated by Django 3.2.12 on 2024-06-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(help_text='Date the event will take place.', null=True, verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(help_text='Time the event will take place.', null=True, verbose_name='Event Time'),
        ),
    ]
